[workspace]

members = [
  "ast",
  "backend",
  "dr-html-backend",
  "dr-html-wasm",
  "cli",
  "eval",
  "parser",
  "opts",
  "test-utils",
]

resolver = "2"

[workspace.lints.clippy]
missing-const-for-fn = "warn"
