[package]
name = "asciidork-backend"
version = "0.3.3"
edition = "2021"
description = "Asciidork backend"
license = "MIT"

[dependencies]
asciidork-ast = { path = "../ast", version = "0.3.0" }
asciidork-opts = { path = "../opts", version = "0.3.0" }

[lints]
workspace = true
