[package]
name = "asciidork-cli"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "asciidork"
path = "src/main.rs"

[dependencies]
asciidork-eval = { path = "../eval" }
asciidork-opts = { path = "../opts" }
asciidork-parser = { path = "../parser" }
asciidork-dr-html-backend = { path = "../dr-html-backend" }
colored = "2.0.4"
bumpalo = { version = "3.14.0", features = ["collections"] }
clap = { version = "4.5.4", features = ["derive"] }
