[package]
name = "asciidork-ast"
version = "0.3.1"
edition = "2021"
description = "Asciidork AST nodes"
license = "MIT"

[dependencies]
bumpalo = { version = "3.15.4", features = ["collections"] }
smallvec = "1.13.2"

[lints]
workspace = true

[lib]
doctest = false
