[package]
name = "asciidork-ast"
version = "0.1.0"
edition = "2021"
description = "Asciidork AST nodes"
license = "MIT"

[dependencies]
bumpalo = { version = "3.15.4", features = ["collections"] }

[lints]
workspace = true

[lib]
doctest = false
