[package]
name = "asciidork-parser"
version = "0.1.0"
edition = "2021"

[dependencies]
asciidork-ast = { path = "../ast" }
bumpalo = { version = "3.14.0", features = ["collections"] }
lazy_static = "1.4.0"
regex = { version = "1.10.2", features = ["std", "use_std"] }

[lib]
doctest = false

[dev-dependencies]
indoc = "2.0.4"
pretty_assertions = "1.4.0"
test-utils = { path = "../test-utils" }
