[package]
name = "parser"
version = "0.1.0"
edition = "2021"

[dependencies]
bumpalo = { version = "3.14.0", features = ["collections"] }
regex = { version = "1.10.2", features = ["std", "use_std"] }

[lib]
doctest = false
