name: basic-ci

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  check:
    strategy:
      matrix:
        target: ['ubuntu-latest', 'windows-latest']
    runs-on: ${{ matrix.target }}
    steps:
      - uses: actions/checkout@v4
      - name: check
        run: cargo check
      - name: clippy
        run: cargo clippy
      - name: fmt
        run: cargo fmt -- --check
      - name: test
        run: cargo test --all --no-fail-fast
      - name: build
        run: cargo build
      - name: wasm
        env:
          RUSTFLAGS: -D warnings -A unused-imports
        run: |
          npm install -g wasm-pack@0.12.1
          cd dr-html-wasm && wasm-pack build --target web
  accept:
    runs-on: ubuntu-latest
    steps:
      - name: install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: '9.4.0'
      - uses: actions/checkout@v4
      - name: build
        run: cargo build
      - uses: actions/checkout@v4
        with:
          repository: 'jaredh159/asciidork-rx-html-acceptance'
          path: 'acceptance'
      - name: install
        run: cd acceptance && pnpm install
      - name: accept
        run: |
          cd acceptance
          node ./check.js "$GITHUB_WORKSPACE/target/debug/asciidork" --verbose

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: -D warnings

concurrency:
  group: ${{ github.ref }}-ci
  cancel-in-progress: true
